Resources:
  DynamoDBSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: DynamoDBTestSecret
      Description: "Dynamically generated secret password for DynamoDB access"
      GenerateSecretString:
        SecretStringTemplate: '{"db.user": "admin"}'
        GenerateStringKey: "db.password"
        PasswordLength: 30